Public Class FormatOutput
    Public Shared Function ScoreToText(ByVal Score As Integer) As String
        Select Case Score
            Case Form1.ValidScores.Miss
                Return "-"
            Case Form1.ValidScores.One
                Return "1"
            Case Form1.ValidScores.Two
                Return "2"
            Case Form1.ValidScores.Three
                Return "3"
            Case Form1.ValidScores.Four
                Return "4"
            Case Form1.ValidScores.Five
                Return "5"
            Case Form1.ValidScores.Six
                Return "6"
            Case Form1.ValidScores.Seven
                Return "7"
            Case Form1.ValidScores.Eight
                Return "8"
            Case Form1.ValidScores.Nine
                Return "9"
            Case Form1.ValidScores.Strike
                Return "X"
            Case Form1.ValidScores.Spare
                Return "/"
            Case Else
                Return ""
        End Select
    End Function
    Public Shared Function TextToScore(ByVal Text As String) As Integer
        Select Case Text
            Case "-"
                Return Form1.ValidScores.Miss
            Case "1"
                Return Form1.ValidScores.One
            Case "2"
                Return Form1.ValidScores.Two
            Case "3"
                Return Form1.ValidScores.Three
            Case "4"
                Return Form1.ValidScores.Four
            Case "5"
                Return Form1.ValidScores.Five
            Case "6"
                Return Form1.ValidScores.Six
            Case "7"
                Return Form1.ValidScores.Seven
            Case "8"
                Return Form1.ValidScores.Eight
            Case "9"
                Return Form1.ValidScores.Nine
            Case "X"
                Return Form1.ValidScores.Strike
            Case "/"
                Return Form1.ValidScores.Spare
            Case Else
                Return Form1.ValidScores.Miss
        End Select
    End Function
End Class
